version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-stretch-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
      - image: circleci/postgres:12.1
        environment:
          POSTGRES_USER: arikablenker
          POSTGRES_DB: sweater-weather_test
          POSTGRES_PASSWORD: ENV['SWEATER_WEATHER_DB_PASSWORD']
    working_directory: ~/sweater-weather
    executor: ruby/default
    steps:
      - checkout
      - run: gem install bundler -v 2.2.8
      - run: bundle install
      - run: bundle exec rake db:create
      - run:
          name: Run tests
          command: bundle exec rspec
      - run: mkdir ~/rspec
      - run:
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml
          when: always
      - store_test_results:
          path: ~/rspec
