version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    working_directory: ~/sweater-weather
    docker:
      - image: circleci/ruby:2.5.3-stretch-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: root
          RAILS_ENV: test
      - image: circleci/postgres:12.1
        environment:
          POSTGRES_USER: arikablenker
          POSTGRES_DB: sweater-weather_test
          POSTGRES_PASSWORD: ENV['SWEATER_WEATHER_DB_PASSWORD']

    executor: ruby/default
    steps:
      - checkout
      - run: gem install bundler -v 2.2.8
      - run: bundle install
      - run: bundle exec rake db:setup
      - run: bundle exec rspec
